export const CATEGORIES = [
  'Celulares',
  'Laptops',
  'Computadores',
  'Monitores',
  'Processadores',
  'Memória RAM',
  'Placas de Vídeo',
  'Armazenamento',
  'Refrigeração',
  'Teclados',
  'Teclados Mecânicos',
  'Mouses',
  'Controles',
  'Áudio',
  'Caixas de Som',
  'Tablets',
  'Leitura',
  'Cadeiras',
  'Acessórios',
]

export const CATEGORY_ICONS = {
  'Celulares':          '📱',
  'Laptops':            '💻',
  'Computadores':       '🖥️',
  'Monitores':          '🖥️',
  'Processadores':      '⚙️',
  'Memória RAM':        '🧩',
  'Placas de Vídeo':    '🎮',
  'Armazenamento':      '💾',
  'Refrigeração':       '❄️',
  'Teclados':           '⌨️',
  'Teclados Mecânicos': '⌨️',
  'Mouses':             '🖱️',
  'Controles':          '🎮',
  'Áudio':              '🎧',
  'Caixas de Som':      '🔊',
  'Tablets':            '📲',
  'Leitura':            '📚',
  'Cadeiras':           '🪑',
  'Acessórios':         '🔌',
}
